# Generated by Django 2.1.5 on 2019-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_team_news'),
        ('users', '0002_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(to='football.Team'),
        ),
    ]
