# Generated by Django 2.1.5 on 2019-01-29 07:36

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(default='none', upload_to=football.models.get_news_image_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
