# Generated by Django 2.1.5 on 2019-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20190129_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
