# Generated by Django 2.1.5 on 2019-02-01 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_newscomment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=16)),
                ('home_team_goals', models.IntegerField(default=0)),
                ('away_team_goals', models.IntegerField(default=0)),
                ('home_team_fouls', models.IntegerField(default=0)),
                ('away_team_fouls', models.IntegerField(default=0)),
                ('home_team_corners', models.IntegerField(default=0)),
                ('away_team_corners', models.IntegerField(default=0)),
                ('home_team_substitutions', models.IntegerField(default=0)),
                ('away_team_substitutions', models.IntegerField(default=0)),
                ('home_team_possesion', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('away_team_possesion', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('report', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.ImageField(upload_to='images/leagues/')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=16)),
                ('appearances', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/players/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.ImageField(upload_to='images/teams/')),
                ('is_club', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeagueSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=16)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_seasons', to='football.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_seasons', to='football.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='leagues',
            field=models.ManyToManyField(related_name='teams', through='football.TeamLeagueSeason', to='football.League'),
        ),
        migrations.AddField(
            model_name='performance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='football.Player'),
        ),
        migrations.AddField(
            model_name='performance',
            name='team_league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='football.TeamLeagueSeason'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='football.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='football.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='football.League'),
        ),
        migrations.AlterUniqueTogether(
            name='teamleagueseason',
            unique_together={('team', 'league', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('player', 'team_league_season')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('home_team_league_season', 'away_team_league_season', 'league', 'season')},
        ),
    ]
