# Generated by Django 2.1.5 on 2019-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20190201_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='news',
            field=models.ManyToManyField(related_name='teams', to='football.News'),
        ),
    ]
