# Generated by Django 2.1.5 on 2019-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20190201_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
