# Generated by Django 2.1.5 on 2019-02-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20190201_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments_count',
        ),
    ]
